#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/tests.v1.schema.json

test_format = 1.0

[default]

    # ------------
    # Tests to run
    # ------------

    # -------------------------------
    # Default args to use for install
    # -------------------------------

    # -------------------------------
    # Commits to test upgrade from
    # -------------------------------

    # testing from another app_id is not supported
    # test_upgrade_from.d615404b72fcffc9c14b8a25cb6335e5ab8158db.name = "Jellyseerr"
