#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source ynh_handle_app_migration
source /usr/share/yunohost/helpers

#=================================================
# STOP SYSTEMD SERVICE
#=================================================
ynh_script_progression "Stopping $app's systemd service..."

ynh_systemctl --service="$app" --action="stop"

#=================================================
# MIGRATE FROM JELLYSEERR TO SEERR
#=================================================
ynh_app_migration_migrate --migration_id="jellyseerr" --migration_list="migration_list"

if [ $migration_process -eq 1 ]
then

	# If a migration has been perform
	# Reload some values changed by the migration process
	install_dir=$(ynh_app_setting_get --app=$app --key=install_dir)

	ynh_script_progression "Making sure dedicated system user exists..."

	# Create a dedicated user (if not existing)
	ynh_system_user_create --username=$app --home_dir="$install_dir"
fi


#=================================================
# ENSURE DOWNWARD COMPATIBILITY
#=================================================
ynh_script_progression "Ensuring downward compatibility..."

ynh_print_info "Adding an API_KEY if not set..."

ynh_app_setting_set_default --app=$app --key="api_key" --value="$(ynh_string_random --length=32)"

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Upgrading source files..."

# Download, check integrity, uncompress and patch the source from manifest.toml
ynh_setup_source --dest_dir="$install_dir" --full_replace --keep="config"

#=================================================
# UPDATE A CONFIG FILE
#=================================================
ynh_script_progression "Updating configuration..."

ynh_config_add --template="seerr.conf" --destination="$install_dir/seerr.conf"

chmod 600 "$install_dir/seerr.conf"
chown $app:$app "$install_dir/seerr.conf"

#=================================================
# REAPPLY SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Upgrading system configurations related to $app..."

# Create a dedicated NGINX config using the conf/nginx.conf template
ynh_config_add_nginx

# Create a dedicated systemd config
ynh_config_add_systemd
yunohost service add "$app" --log="/var/log/$app/$app.log"

# Use logrotate to manage application logfile(s)
ynh_config_add_logrotate
touch /var/log/$app/$app.log

#=================================================
# BUILD APP
#=================================================
ynh_script_progression "Building App... This may take quiet some time"

pushd $install_dir
	export CYPRESS_INSTALL_BINARY=0
    ynh_hide_warnings corepack enable && corepack prepare pnpm@10 --activate
    ynh_hide_warnings ynh_exec_as_app CYPRESS_INSTALL_BINARY=0 NODE_OPTIONS="--max-old-space-size=3000" pnpm install --frozen-lockfile --aggregate-output
    ynh_hide_warnings ynh_exec_as_app CYPRESS_INSTALL_BINARY=0 NODE_OPTIONS="--max-old-space-size=3000" pnpm build

    #remove unneeded files
    ynh_hide_warnings ynh_exec_as_app pnpm prune --prod --ignore-scripts
    ynh_hide_warnings ynh_exec_as_app pnpm store prune
    ynh_safe_rm src
    ynh_safe_rm server
    ynh_safe_rm .next/cache
popd

chown -R $app:$app "$install_dir"

#=================================================
# FINISH MIGRATION PROCESS
#=================================================

if [ $migration_process -eq 1 ]
then
	ynh_app_migration_post_migrate
fi

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

# Start a systemd service
ynh_systemctl --service="$app" --action="start" --log_path="/var/log/$app/$app.log"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Upgrade of $app completed"
